kind: pipeline
type: docker
name: default

steps:
- name: deploy-pkg
  image: plugins/npm
  settings:
    username: 
      from_secret: pkg_username
    password: 
      from_secret: pkg_password
    email: 
      from_secret: pkg_email
    registry: "http://pkg.saltboxgames.com:4873"
